FROM bellsoft/liberica-openjdk-alpine:17 AS builder
WORKDIR application
COPY mock-echo-tcp-server/gradle gradle
COPY mock-echo-tcp-server/gradlew gradlew
COPY mock-echo-tcp-server/build.gradle.kts build.gradle.kts
RUN sed -i 's/\r$//' gradlew # For windows os
COPY mock-echo-tcp-server/src src
RUN ./gradlew bootJar
RUN java -Djarmode=layertools -jar build/libs/*.jar extract

FROM bellsoft/liberica-openjre-alpine:17
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]